### ISSUE TITLE
[Official] What I'm doing about releasing the code?

### ISSUE THREAD

**Issue by DavidXu-JJ** [DavidXu-JJ/DebSDF#4]
Hi everyone,
Thanks for your attention to our work.

I'm currently actively organizing the code for release.
Also, I'm trying to add some comments to the code to keep it in alignment with the formulation and section of our paper. (To reduce the difficulties of code reading)

I'm also rerunning the code to make sure everything is fine.
Rerunning test of the code may take some days. 
Please kindly wait for severals days if you are now willing to access our manuscript code.
Thanks for your understanding.

Best,
Jingwei

**Comment by zhanghaoyu816** [comment]
nice work! looking forward it

**Comment by DavidXu-JJ** [comment]
The code has been released. Please view the README for details.
