### ISSUE TITLE
about F-score

### ISSUE THREAD

**Issue by HuTaoMylove** [DavidXu-JJ/DebSDF#5]
Sorry to bother you again. I use your setting in scannet on 4090 torch 1.13.1 cuda1.17.1，but I can't get same result in your paper.My results are as follow.I have no idea about this prob as the performance should not be so degraded that caused by the difference of cuda and torch.

![屏幕截图 2024-06-12 134735](https://github.com/DavidXu-JJ/DebSDF/assets/88564974/1b0f0825-4b54-42bd-9309-1d66bbff85d1)

**Comment by DavidXu-JJ** [comment]
Hi Mingzhi,
Thanks for your attention to our work.
I can share our experiment data with you.

![image](https://github.com/DavidXu-JJ/DebSDF/assets/68705456/62a07bdb-9d6f-46e8-9d4c-1774120f1f71)

In the table above, the Left side is our experiment in the original paper. That should align with our table on paper.
The right side is the experiment I tested before the code release. That's even better than the original paper when I tested this code several days before.

I run this scene just for one time during my testing, and maybe you also run this for one time. There may be some random issue with each running.

If you need me to release my checkpoint for evaluation, I can help to give a guideline. (But the metrics maybe a little better than the original paper.)

**Comment by DavidXu-JJ** [comment]
It seems that scan4 is the main degenerating scene.
I can give you the visualization of this scene's reconstruction for your reference, which was produced just a few days ago.

![image](https://github.com/DavidXu-JJ/DebSDF/assets/68705456/843acfc1-d3fb-41a3-b324-e840d6ad8e46)

**Comment by DavidXu-JJ** [comment]
Empirically,
this scene has the possibility to degenerate because of improper initialization.

If you wish to get the result with your machine, I suggest to rerun the code.

If you strongly wish to access our checkpoint, please tell me.

**Comment by DavidXu-JJ** [comment]
Hello Mingzhi,

I have just updated our official checkpoint for evaluation.

Please check out https://github.com/DavidXu-JJ/DebSDF?tab=readme-ov-file#official-checkpoint-evaluation.

All these evaluations should align with our paper.

Issue closed.
