### ISSUE TITLE
About cameras.npz

### ISSUE THREAD

**Issue by tangfqj** [DavidXu-JJ/DebSDF#7]
Hi, thanks very much for open-sourcing this impressive work!

I wonder if the `cameras.npz` file was missed in the preprocessed `scannet.zip`, since it is required during training. Or should I generate it myself with certain script?

Thanks so much~

**Comment by DavidXu-JJ** [comment]
Hi,
Please consider adapting your preprocess script from this MonoSDF script: https://github.com/autonomousvision/monosdf/blob/main/preprocess/scannet_to_monosdf.py

Our data structure is consistent with MonoSDF.
If you can run with MonoSDF code base, you can also run with our method/code.
Best,
Jingwei

**Comment by DavidXu-JJ** [comment]
I find there are some mistakes in all my uploaded .zip data.
Thank you for your reminding and pointing it out.
I will quickly update it then.

**Comment by tangfqj** [comment]
This preprocess script works for me. Thanks for your reply!

**Comment by DavidXu-JJ** [comment]
Hi! Thanks for your remind.
I have just updated the corrected .zip data.
Previously, when I downloaded the data from the cluster server, some files had not yet been downloaded.
This causes some files to be missing.

Currently, I am updating the data on Google Drive with the complete .zip file directly downloaded from the cluster server.
If you still wish to use our preprocess data, you can download it from the official link again!
Just the same way as is mentioned in README.
Please let me know if there is any problem with the released data.
